# -*- coding: utf-8 -*-
"""Adivinhacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6D_MJS3G-Ax2l6E6lsOtQBrs-p-m8kC
"""

from random import randint

print("------ Iniciando o Super Game ------")

tesouro = randint(0,100)
chute = 0
chances = 10

while chute != tesouro:
  chute = input("Qual numero você acha que é?")
  if chute.isnumeric():
    chute = int(chute)
    chances = chances - 1
    if chute == tesouro:
      print('')
      print('Parabéns! Você acertou')
      print('O numero era {} e você ainda tinha {} chances'.format(tesouro,chances))
      print('')
      break;
    else:
      print('')
      if chute > tesouro:
        print('Você errou! Dica: É um numero menor!')
      else:
        print('Você errou! Dica: É um numero maior!')
      print('Você ainda possui {} chances'.format(chances))
    if chances == 0 :
      print('')
      print(f'Suas chances acabaram. O numero era: {tesouro}. Você Perdeu')
      print('')
      break;
  else:
    print('')
    print('Você insiriu letras, é apenas numeros')
    print(f'Você ainda possui {chances} chances')
    print('')
print("------ GAME OVER ------")