# -*- coding: utf-8 -*-
"""Calculadora_IR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiRsKr_7fTOWnBeTy0wReq2is_HH3k0p
"""

salario = float(input("Qual seu salario para calcular o IR?"))

imposto = 0
if salario > 3000:
  imposto = imposto + ((salario - 3000) * 0.35)
if salario > 1000:
  imposto = imposto + ((salario - 1000) * 0.35)

print("Salario: R$%6.2f \nImposto a Pagar: R$%6.2f" % (salario, imposto))

cidades = ["São Paulo", "Rio de Janeiro", "Belo Horizonte"]
nome = "Caio"
print(cidades[0])
print(nome[0])

print("---------------")

contador = 0
while contador < 3:
  print(cidades[contador])
  contador = contador + 1

print("---------------")

for letra in nome:
  print(letra)

print("---------------")

for cidade in cidades:
  print(cidade)

frutas = ["Laranja", "pera", "maça", "abacate", "acerola", "uva", "tomate"]

def mostrafruta(valor,trexto):
  print(frutas[valor], trexto)

mostrafruta(2,"adoro")
mostrafruta(1,"odeio")

imposto = 0
def calcular(salario):
  tabela_ir = [
      {"faixa":(0,1903.98),"aliquota": 0,"deducao":0},
      {"faixa": (1903.99, 2826.65), "aliquota": 7.5, "deducao": 142.80},
      {"faixa": (2826.66, 3751.05), "aliquota": 15, "deducao": 354.80},
      {"faixa": (3751.06, 4664.68), "aliquota": 22.5, "deducao": 636.13},
      {"faixa": (4664.69, float("inf")), "aliquota": 27.5, "deducao": 869.36}
  ]
  for faixa in tabela_ir:
      if salario > faixa["faixa"][0] and salario <= faixa["faixa"][1]:
          imposto = (salario * faixa["aliquota"]) / 100 - faixa["deducao"]
          break
  return imposto
salario_bruto = float(input("Informe o seu Salario Bruto!"))
imposto = calcular(salario_bruto)
print(f"O imposto de renda devido é de R${imposto:.2f}")

